version: '2.6'
name: cryptobot
services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: cryptobot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"


  bot:
    image: tiafanasev/cryptobot:bot
    depends_on:
      - db
    ports:
      - "8080:8080"